require "rake/clean"
CLEAN.include("*.class")

rule ".class" => ".java" do |t|
  sh "javac #{t.source}", verbose: false
end

task run: Rake::FileList.new("*.java").ext(".class") do |t|
  sh "java Hello", verbose: false
end
